### ISSUE TITLE
url에 언더 바가 포함된 일부 갤러리에서 글 목록이 보이지 않는 문제

### ISSUE THREAD

**Issue by geeksbaek** [lesomnus/chrome.dcsm#10]
언더 바(_)가 포함된 일부 갤러리에서 개념글 전환시 글 목록이 보이지 않는 문제가 있는 것 같습니다. 언더 바 때문인지는 확실하지 않으나, 확인한 갤러리는 다음과 같습니다.

언더 바가 포함되고 글 목록이 보이지 않는 문제가 발생하는 갤러리
http://gall.dcinside.com/board/lists/?id=baseball_new4
http://gall.dcinside.com/board/lists/?id=event_voicere
http://gall.dcinside.com/board/lists/?id=cartoon_s

언더 바가 포함되었지만 글 목록이 정상적으로 보이는 갤러리
http://gall.dcinside.com/board/lists/?id=p_color

**Comment by lesomnus** [comment]
저는 정상적으로 보입니다. 다른분 확인 부탁드립니다.

**Comment by KimKyung-man** [comment]
저도 같은 현상이 있네요 . 

버전 48.0.2564.116 m 입니다.

**Comment by lesomnus** [comment]
저도 48.0.2564.116m이네요... .1.0.0버전에서 테스트하셨나요?

**Comment by lesomnus** [comment]
아 저도 그러네요. 개념글 목록은 확인안했었는데..ㅋㅋ

**Comment by lesomnus** [comment]
에러나는 이유 찾았습니다. 글목록 요청이 목록 자체는 AJAX요청이 막혀 있어서 1번글 보기로 목록을 가져오게 해놨는데, 해당 갤러리들은 1번글이 삭제된것 같습니다. 보통 1번글이면 공지글일텐데 이상하네요...

**Comment by geeksbaek** [comment]
예를 들어 http://gall.dcinside.com/board/view/?id=baseball_new4&**no=1** 이라는 url을 요청해 목록을 가져온다는 것인가요?

**Comment by lesomnus** [comment]
넵넵. 글목록만 요청하면 안되더라구요... 방금 모바일 페이지로 글목록 요청할려고 했는데 user-agent 때문에 리다이렉트 페이지가 응답됩니다.. ㅠ_ㅠ Chrome API로 user-agent 바꿔보려는데 공부해야할게 좀 있네요... 내일 천천히 볼려고합니다.

**Comment by lesomnus** [comment]
아 근데 생각해보니깐, 일반 목록은 보이는데 개념글만 안보이는것도 이상하네요. 1번글이 없으면 일반 목록도 안보여야하는데.

**Comment by KimKyung-man** [comment]
실제로 일반 목록에서는 no=1 은 있던 없건, 파라메터가 있는 것만 확인하기때문에, 작동을 하는 것이였습니다.
일반 목록도 쿼리 스트링에서 no 을 빼주었을때는, 동작하지 않습니다.
따라서 근본적 원인은 게시판 번호로 페이지를 파싱하는 것이 아닌 임의의 글 넘버를 이용해서 페이지를 가져와, 파싱하기 때문이였고.. 
확인해보니 dc 서버 내부적으로는 RequestHeader / accept 값만 확인해서 페이지를 내려주기 때문에 ..
해당 부분만 명시적으로 추가를 해서 글 넘버 + 페이지 번호를 이용해서 페이지 파싱을 하는 방식이 아닌 페이지 번호만을 이용해서 파싱하도록 수정을 해보니, 잘 동작하는 것 같습니다.

**Comment by KimKyung-man** [comment]
[버그 픽스](https://github.com/lesomnus/chrome.dcsm/pull/11) 
제 것에선 동작을 하는데, 수정은 된 듯 싶은데 ... 잘 동작하는지 확인 부탁드립니다.

**Comment by lesomnus** [comment]
하 삽질할뻔했네요ㅋㅋ 정상적으로 출력되는것 확인했고, 병합도 했습니다. 기여해주셔서 감사합니다.

**Comment by geeksbaek** [comment]
크롬 웹스토어에 올라간 앱은 따로 업데이트해야 수정사항이 적용되나요?
github의 소스를 베이스로 자동으로 업데이트되는 기능이 있었으면 좋을텐데 아쉽네요.

**Comment by lesomnus** [comment]
넵.. 제가 업로드를 새로 해야합니다.. 버그는 고쳐졌으니 이슈 닫겠습니당.
