### ISSUE TITLE
댓글 submit 상태 업데이트

### ISSUE THREAD

**Issue by KimKyung-man** [lesomnus/chrome.dcsm#17]
댓글을 연달아 달면, 가끔 submit이 계속 diable된 상태에서 돌아오지 않음

**Comment by lesomnus** [comment]
푸갤에 뻘글하나 싸고 테스트좀 해바야겠네여

**Comment by lesomnus** [comment]
혹시 가끔 댓글요청 ajax에서 error가 떠서 그런게 아닐까요.. 방금 테스트해봤는데 문제 없더군요

**Comment by lesomnus** [comment]
error를 재현할수도 없는 노릇이고, 그리고 코드를 보면 에러가 떠도 성공할떄와 같은 콜백함수를 호출하도록 해뒀네요...
