### ISSUE TITLE
동영상 로드 안됨.

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/chrome.dcsm#2]
동영상 로드가 안된다는 피드백을 받았습니다. 확인은 아직 못했습니다.

관련 코드는 src/modules/control/content.js#38 에서 확인할 수 있습니다.

**Comment by KimKyung-man** [comment]
잘 되는 것 같은데 ..
http://gall.dcinside.com/board/view/?id=dci_scrap&no=53821&page=1

**Comment by lesomnus** [comment]
그러게요.. 근데 저도 다른분 한테서 받은 의견이라.. 좀 더 확인해보고 문제 없으면 29날 이슈 닫겠습니다.
