### ISSUE TITLE
필요한 옵션을 말해주세요.

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/chrome.dcsm#25]
현재 받은 피드백으로는,
- 목록 View 좌/우 선택가능
- 댓글 꼬릿말

가 있습니다.

**Comment by geeksbaek** [comment]
유동닉으로 리플이나 글을 한번 작성하면 닉네임과 비밀번호를 저장하여 이후에는 자동으로 폼이 완성되면 좋겠습니다.
