### ISSUE TITLE
글 미리 읽기.

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/chrome.dcsm#5]
글을 읽어야만 해당 글쓴이의 IP 정보와 모바일에서 작성된 것인지에 대한 정보를 알 수 있습니다.
사용자가 글을 읽지 않더라도 읽기 요청을 보내어 미리 정보를 알 수 있게 해달라는 피드백을 받았습니다.
물론, 모바일 앱이 아니므로 사용자에게 부담은 적을 것이나 DC서버에 부담을 주게 될까 망설여 집니다.
해당 기능에 대한 적절한 토론이 이루어진 후 기능추가를 했으면 좋겠습니다.

**Comment by KimKyung-man** [comment]
어차피 글을 클릭하면 바로 읽어볼 수 있게 되어있으니..
괜히 디씨측 서버에 부담만 주는게 아닌가 싶긴 합니다. 

이 기능이 꼭 필요한 기능일까 라는 생각을 해보면 ..
의문이 조금 드는 감이 있네요
