### ISSUE TITLE
컨벤션 질문

### ISSUE THREAD

**Issue by KimKyung-man** [lesomnus/chrome.dcsm#8]
현재 컨벤션이 카멜케이스, 파스칼, 언더스코어로 혼용되어있는데 특정 규칙이 있는 것인지요 ? 
딱히 규칙이 없이 되있는 것 같지만.... 혹시나해서

**Comment by lesomnus** [comment]
제성합니다. 급하게 만들어서 그렇습니다. 언더스코어를 주로 씁니다. 단, getter, setter의 경우 카멜케이스를 씁니다. 파스칼 표기법이 적용된것은 new 로 인해 생성될 수 있는 객체를 뜻합니다. 목록의 아이템인 ListItem이 그러한 경우입니다.

**Comment by lesomnus** [comment]
맨앞에 언더스코어로 사용되는 변수는 임시변수이거나 private인데, 임시 변수의경우 변수이름에서 temp라는 단어가 이미 들어가있습니다. 이부분에 대해서는 개선이 필요하다고 생각합니다.

**Comment by KimKyung-man** [comment]
현재 단일 메소드에서도 카멜이 아닌 타 케이스가 적용되있는 경우가 있는데, 이는 진행해나가면서 고칠 수 있는 부분이겠네요 ~^^
